length_in_x: 4.0
length_in_y: 4.0
position_x: 0.0
position_y: 0.0
resolution: 0.1
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.01
fused_map_publishing_rate: 2.0
enable_skip_lower_points: false
scanning_duration: 0.01
remove_penetrated_points_rate: 5.0
